name: python
on: [push]
jobs:
  tox-py312:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'requirements-test.txt'
      - run: pip install tox
      - run: tox -e py312
